app_name: BODAI
version: 0.1.0

server:
  host: 0.0.0.0
  port: 8000
  reload: true

logging:
  level: INFO
  file: logs/bodai.log

database:
  url: sqlite:///data/bodai.sqlite3
  backup_dir: backups/
  backup_retain_days: 14
